#%RAML 1.0 DataType
displayName: returns a response to either supplier or customer.
description: This returns a response to either supplier or customer.
type: object
properties:
  userId :
    description:  Unique identifier for supplier or customer
    type: number
    example: 123456